# credo:disable-for-this-file Credo.Check.Readability.Specs
defmodule Connect4.Mailer do
  @moduledoc """
  Swoosh mailer, auto-generated by Phoenix.
  """
  use Swoosh.Mailer, otp_app: :connect4
end
